/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import deu.cse.lectureroomreservation2.client.Client;

/**
 *
 * @author Jimin
 */
public class AdminMainView extends javax.swing.JFrame {

/**
     * Creates new form AdminMainView
     */
    private final Client client;
    private final String userId;

    public AdminMainView(String userId, Client client) {
        this.userId = userId;
        this.client = client;

        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUserManagement = new javax.swing.JButton();
        btnReservationHistory = new javax.swing.JButton();
        btnTimetableManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        prof_pass_change = new javax.swing.JButton();
        prof_LogOut = new javax.swing.JButton();
        btnViewRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUserManagement.setText("👤 사용자 관리");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnReservationHistory.setText("📅 예약 내역 조회");
        btnReservationHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationHistoryActionPerformed(evt);
            }
        });

        btnTimetableManagement.setText("🕒 강의실 일정 관리");
        btnTimetableManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimetableManagementActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setText("Admin Main");
        jLabel1.setToolTipText("");

        prof_pass_change.setText("비밀번호 변경");
        prof_pass_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prof_pass_changeActionPerformed(evt);
            }
        });

        prof_LogOut.setText("로그아웃");
        prof_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prof_LogOutActionPerformed(evt);
            }
        });

        btnViewRoom.setText("강의실 현황 조회");
        btnViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prof_pass_change)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(prof_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReservationHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimetableManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservationHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimetableManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prof_pass_change, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prof_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        // TODO add your handling code here:
        new UserManagementView(client).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnReservationHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationHistoryActionPerformed
        // TODO add your handling code here:
        new ReservationHistoryView(client).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservationHistoryActionPerformed

    private void btnTimetableManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimetableManagementActionPerformed
        // TODO add your handling code here:
        new RoomScheduleManagementView(client).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTimetableManagementActionPerformed

    private void prof_pass_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prof_pass_changeActionPerformed
        // TODO add your handling code here:
        ChangePassView frameA = new ChangePassView();
        frameA.setStreams(client.getOutputStream(), client.getInputStream());
        frameA.setUserId(userId);
        frameA.setSize(300, 450);           // 창 크기 설정 (적당히 보기 좋은 크기)
        frameA.setLocationRelativeTo(null); // 화면 가운데 정렬
        frameA.setVisible(true);            // 화면에 보이게 만들기
    }//GEN-LAST:event_prof_pass_changeActionPerformed

    private void prof_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prof_LogOutActionPerformed
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(this, "로그아웃 하시겠습니까?", "로그아웃", javax.swing.JOptionPane.YES_NO_OPTION);

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            String currentIp = "localhost";
            if (client != null) {
                currentIp = client.getServerIp(); // IP 저장
                client.logout();
            }
            this.dispose();
            new LoginFrame(currentIp).setVisible(true); // IP 전달
        }
    }//GEN-LAST:event_prof_LogOutActionPerformed

    private void btnViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRoomActionPerformed
        // TODO add your handling code here:
        // ViewRoom 화면을 "A" (관리자) 권한으로 엽니다.
        // 마지막 인자 null은 예약 변경 모드가 아니라는 뜻
        ViewRoom viewRoom = new ViewRoom(client, userId, "A", null);
        viewRoom.setVisible(true);
        this.dispose(); // 현재 관리자 메인 화면은 닫기
    }//GEN-LAST:event_btnViewRoomActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservationHistory;
    private javax.swing.JButton btnTimetableManagement;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton prof_LogOut;
    private javax.swing.JButton prof_pass_change;
    // End of variables declaration//GEN-END:variables
}
