/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import deu.cse.lectureroomreservation2.client.view.StudentMainMenu;
import deu.cse.lectureroomreservation2.client.view.ProfessorMainMenu;
import deu.cse.lectureroomreservation2.client.Client;
import java.io.*;
import javax.swing.SwingUtilities;


/**
 *
 * @author User
 */
public class LoginFrame extends javax.swing.JFrame {
    private String server_ip = "localhost";

    /**
     * Creates new form LoginForm
     */
    public LoginFrame() {
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }
    
    public LoginFrame(String server_ip) {
        this.server_ip = server_ip;
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        stuRadio = new javax.swing.JRadioButton();
        profRadio = new javax.swing.JRadioButton();
        adminRadio = new javax.swing.JRadioButton();
        LoginButton = new javax.swing.JButton();
        PWtext = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LectureRoom Reservation");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel4.setText("PW");

        IDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextActionPerformed(evt);
            }
        });

        stuRadio.setText("학생");
        stuRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRadioActionPerformed(evt);
            }
        });

        profRadio.setText("교수");
        profRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profRadioActionPerformed(evt);
            }
        });

        adminRadio.setText("관리자");
        adminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioActionPerformed(evt);
            }
        });

        LoginButton.setText("로그인");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDtext)
                            .addComponent(PWtext)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stuRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profRadio)
                        .addGap(28, 28, 28)
                        .addComponent(adminRadio))
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(IDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PWtext, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profRadio)
                    .addComponent(adminRadio)
                    .addComponent(stuRadio))
                .addGap(31, 31, 31)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String id = IDtext.getText();
        String pw = new String(PWtext.getPassword()); // JPasswordField는 이렇게 사용해야 함
        String role = null;     // 역할 라디오 버튼에서 선택된 값 가져오기

        if (stuRadio.isSelected()) {
            role = "S";
        } else if (profRadio.isSelected()) {
            role = "P";
        } else if (adminRadio.isSelected()) {
            role = "A";
        }

        // 빈칸을 남기고 로그인 버튼을 눌렀을 경우.
        if (id == null || pw == null || role == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "해당 항목을 모두 입력하십시오.");
            return;
        }

        try {
            // TCP 서버에 접속
            deu.cse.lectureroomreservation2.client.Client client = new deu.cse.lectureroomreservation2.client.Client(server_ip, 5000);
            client.sendLoginRequest(id, pw, role);  // 로그인 요청 전송

            try {
                deu.cse.lectureroomreservation2.common.LoginStatus status = client.receiveLoginStatus();  // 로그인 응답 수신

                if (!status.isLoginSuccess()) {
                    if ("WAIT".equals(status.getRole())) {
                        javax.swing.JOptionPane.showMessageDialog(this, "접속 인원 초과.");
                    } else if ("DUPLICATE".equals(status.getRole())) {
                        javax.swing.JOptionPane.showMessageDialog(this, "이미 로그인 중인 계정입니다.");
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "로그인 실패! ID, 비밀번호 또는 역할이 일치하지 않습니다.");
                    }
                    client.logout();
                    return;
                }

                // 로그인 성공 → 역할에 따라 메인 화면 분기
                String serverRole = status.getRole();      // STUDENT / PROFESSOR / ADMIN
                String message = status.getMessage();      // "ACTIVE" 또는 "WAITING:n" 또는 null

// 1) 바로 입장 가능한 상태 (ACTIVE 또는 message 없음)
                if (message == null || message.isEmpty() || "ACTIVE".equals(message)) {
                    openMainFrame(serverRole, id, client);
                    return;
                }

// 2) 대기열 상태인 경우: "WAITING:n"
                if (message.startsWith("WAITING:")) {
                    String pos = message.substring("WAITING:".length());

                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "현재 서버 접속 인원이 가득 찼습니다.\n"
                        + "현재 " + pos + "번째로 대기 중입니다.\n"
                        + "자리가 나면 자동으로 입장합니다."
                    );  

                    final LoginFrame frame = this;

                    Thread waitThread = new Thread(() -> {
                        try {
                            var out = client.getOutputStream();
                            var in = client.getInputStream();

                            while (true) {
                                // 3초마다 상태 확인
                                Thread.sleep(3000);
                            
                                synchronized (client) {
                                    out.writeUTF("CHECK_QUEUE");
                                    out.flush();
                                
                    String response = in.readUTF();   // ACTIVE / WAITING:n / NONE
                    System.out.println("CHECK_QUEUE 응답: " + response);

                    if ("ACTIVE".equals(response)) {
    // 입장 가능 → EDT에서 원래 쓰던 코드 그대로 실행
                        SwingUtilities.invokeLater(() -> {
                            try {
                                switch (serverRole) {
                                    case "STUDENT" -> {
                                        new StudentMainMenu(id, client).setVisible(true);
                                    }
                                    case "PROFESSOR" -> {
                                        new ProfessorMainMenu(id, client).setVisible(true);
                                    }
                                    case "ADMIN" -> {
                                        new AdminMainView(id, client).setVisible(true);
                                    }
                                    default -> {
                                        javax.swing.JOptionPane.showMessageDialog(
                                                frame, "알 수 없는 사용자 유형입니다.");
                                        return;
                                    }
                                }
                                frame.dispose();   // 로그인 창 닫기
                            } catch (Exception ex) {
                                ex.printStackTrace();
                                javax.swing.JOptionPane.showMessageDialog(
                                        frame,
                                        "대기 중 입장 처리 중 오류가 발생했습니다. 다시 로그인해 주세요."
                                );
                            }
                        });
                        break;
                    }


                    if ("NONE".equals(response)) {
                        // 대기열에서 제거됨
                        SwingUtilities.invokeLater(() -> {
                            javax.swing.JOptionPane.showMessageDialog(
                                frame,
                                "대기열에서 제거되었습니다. 다시 로그인해 주세요."
                            );
                        });
                        client.logout();
                        break;
                    }

                    // WAITING:n 이면 계속 루프
                }
            }
        } catch (Exception ex) {
                            ex.printStackTrace();
                            SwingUtilities.invokeLater(() -> {
                                javax.swing.JOptionPane.showMessageDialog(
                                    frame,
                                    "대기 중 오류가 발생했습니다. 다시 로그인해 주세요."
                                );
                            });
                            try {
                                client.logout();
                            } catch (Exception ignore) {}
                        }
                    });

                    waitThread.setDaemon(true);
                    waitThread.start();
                    return;
                }

                // 3) 그 외 이상한 상태
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                "알 수 없는 로그인 상태입니다: " + message
                );
                client.logout();


                this.dispose();  // 현재 로그인 창 닫기

            } catch (EOFException e) {
                // 서버에서 소켓을 바로 끊은 경우 (ex: 인원 초과 처리 등)
                javax.swing.JOptionPane.showMessageDialog(this, "접속 인원이 가득 찼거나 서버에서 연결이 종료되었습니다.");
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "서버 응답 처리 중 오류가 발생했습니다.");
            }

        } catch (IOException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "서버에 연결할 수 없습니다.");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void stuRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuRadioActionPerformed

    private void profRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profRadioActionPerformed

    private void adminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
        // 로그인 성공 후, 역할에 따라 메인 화면 여는 공통 메서드
    private void openMainFrame(String serverRole, String id, deu.cse.lectureroomreservation2.client.Client client) {
        switch (serverRole) {
            case "STUDENT" -> {
                new StudentMainMenu(id, client).setVisible(true);
            }
            case "PROFESSOR" -> {
                new ProfessorMainMenu(id, client).setVisible(true);
            }
            case "ADMIN" -> {
                new AdminMainView(id, client).setVisible(true);
            }
            default -> {
                javax.swing.JOptionPane.showMessageDialog(this, "알 수 없는 사용자 유형입니다.");
                return;
            }
        }

        // 로그인 창 닫기
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtext;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PWtext;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton profRadio;
    private javax.swing.JRadioButton stuRadio;
    // End of variables declaration//GEN-END:variables
}
