/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import deu.cse.lectureroomreservation2.client.view.StudentMainMenu;
import deu.cse.lectureroomreservation2.client.view.ProfessorMainMenu;
import deu.cse.lectureroomreservation2.client.Client;
import java.io.*;

/**
 *
 * @author User
 */
public class LoginFrame extends javax.swing.JFrame {
    private String server_ip = "localhost";

    /**
     * Creates new form LoginForm
     */
    public LoginFrame() {
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }
    
    public LoginFrame(String server_ip) {
        this.server_ip = server_ip;
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        stuRadio = new javax.swing.JRadioButton();
        profRadio = new javax.swing.JRadioButton();
        adminRadio = new javax.swing.JRadioButton();
        LoginButton = new javax.swing.JButton();
        PWtext = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LectureRoom Reservation");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel4.setText("PW");

        IDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextActionPerformed(evt);
            }
        });

        stuRadio.setText("학생");
        stuRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRadioActionPerformed(evt);
            }
        });

        profRadio.setText("교수");
        profRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profRadioActionPerformed(evt);
            }
        });

        adminRadio.setText("관리자");
        adminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioActionPerformed(evt);
            }
        });

        LoginButton.setText("로그인");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDtext)
                            .addComponent(PWtext)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stuRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profRadio)
                        .addGap(28, 28, 28)
                        .addComponent(adminRadio))
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(IDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PWtext, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profRadio)
                    .addComponent(adminRadio)
                    .addComponent(stuRadio))
                .addGap(31, 31, 31)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // 1. 입력값 가져오기
        String id = IDtext.getText();
        String pw = new String(PWtext.getPassword());
        String role = null;

        if (stuRadio.isSelected()) role = "S";
        else if (profRadio.isSelected()) role = "P";
        else if (adminRadio.isSelected()) role = "A";

        if (id.isEmpty() || pw.isEmpty() || role == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID, 비밀번호, 역할을 모두 입력해주세요.");
            return;
        }

        // ---------------------------------------------------------
        // 2. [대기 알림창 UI 생성]
        // ---------------------------------------------------------
        final javax.swing.JDialog waitDialog = new javax.swing.JDialog(this, "접속 대기 중...", true); // true = 모달(다른 작업 불가)
        waitDialog.setSize(400, 200);
        waitDialog.setLocationRelativeTo(this);
        waitDialog.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE); // X 버튼 눌러도 안 닫히게 막음(강제 대기)
        
        // 대기창 내부 디자인
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout());
        javax.swing.JLabel titleLabel = new javax.swing.JLabel("<html><h2 style='text-align:center;'>⏳ 접속 대기 중...</h2></html>", javax.swing.SwingConstants.CENTER);
        javax.swing.JLabel descLabel = new javax.swing.JLabel("<html><div style='text-align:center;'>"
                + "현재 접속 인원이 초과되었습니다.<br>"
                + "서버에 대기열이 등록되었습니다.<br><br>"
                + "<b><font color='blue'>빈자리가 생기면 자동으로 로그인됩니다.</font></b><br>"
                + "(확인 버튼을 누르지 않아도 됩니다)</div></html>", javax.swing.SwingConstants.CENTER);
        
         // 취소 버튼 (기다리다 지쳐서 취소하고 싶을 때)
        javax.swing.JButton cancelBtn = new javax.swing.JButton("대기 취소 / 종료");
        cancelBtn.addActionListener(e -> System.exit(0)); // 프로그램 종료 (또는 소켓 끊기 구현 가능)
        
        panel.add(titleLabel, java.awt.BorderLayout.NORTH);
        panel.add(descLabel, java.awt.BorderLayout.CENTER);
        panel.add(cancelBtn, java.awt.BorderLayout.SOUTH);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        waitDialog.add(panel);


        // 사용될 변수들을 final 또는 effectively final로 사용하기 위해 로컬 변수에 할당
        final String finalRole = role;
        final String serverIp = this.server_ip; // LoginFrame의 멤버변수

        // 3.별도의 스레드에서 서버 접속 시도
        new Thread(() -> {
            try {
                // (1) TCP  서버 연결 시도
                deu.cse.lectureroomreservation2.client.Client client = new deu.cse.lectureroomreservation2.client.Client(serverIp, 5000);
                
                // (2) 로그인 요청 전송
                client.sendLoginRequest(id, pw, finalRole);

                // (3) 응답 대기 (여기가 핵심!)
                // 서버 프록시(Proxy)가 자리가 날 때까지 여기서 응답을 안 줍니다.
                // 따라서 클라이언트는 이 줄에서 멈춰있게 됩니다. (Blocking)
                deu.cse.lectureroomreservation2.common.LoginStatus status = client.receiveLoginStatus();

                /// ---------------------------------------------------------
                // 4. [자동 로그인] 서버 응답이 오면 실행 (자리가 났다는 뜻)
                // ---------------------------------------------------------
                javax.swing.SwingUtilities.invokeLater(() -> {
                    waitDialog.dispose(); // 대기 알림창 닫기 (자동)

                    if (!status.isLoginSuccess()) {
                        // 실패 시 메시지 처리
                        String msg = "로그인 실패";
                        if ("DUPLICATE".equals(status.getRole())) msg = "이미 로그인 중인 계정입니다.";
                        else msg = "ID 또는 비밀번호가 일치하지 않습니다.";
                        
                        javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, msg);
                        client.logout();
                        return;
                    }

                    // 로그인 성공 -> 메인 화면으로 자동 이동
                    try {
                        
                        switch (status.getRole()) {
                            case "STUDENT" -> {
                                new StudentMainMenu(id, client).setVisible(true);
                                // 공지사항 확인 (별도 스레드 권장)
                                new Thread(() -> {
                                    try { client.checkAndShowNotices(null); } catch (Exception e) {}
                                }).start();
                            }
                            case "PROFESSOR" -> new ProfessorMainMenu(id, client).setVisible(true);
                            case "ADMIN" -> new AdminMainView(id, client).setVisible(true);
                        }
                        LoginFrame.this.dispose(); // 로그인 창 닫기
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                });

            } catch (IOException | ClassNotFoundException e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    waitDialog.dispose(); // 에러 나면 창 닫기
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, "서버 연결 오류: " + e.getMessage());
                });
            }
        }).start();

        // 5. 스레드 시작 후 바로 알림창 띄우기 (코드 실행은 여기서 멈추지 않고 위 스레드가 돎)
        waitDialog.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void stuRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuRadioActionPerformed

    private void profRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profRadioActionPerformed

    private void adminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtext;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PWtext;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton profRadio;
    private javax.swing.JRadioButton stuRadio;
    // End of variables declaration//GEN-END:variables
}
