/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import deu.cse.lectureroomreservation2.client.view.StudentMainMenu;
import deu.cse.lectureroomreservation2.client.view.ProfessorMainMenu;
import deu.cse.lectureroomreservation2.client.Client;
import java.io.*;

/**
 *
 * @author User
 */
public class LoginFrame extends javax.swing.JFrame {
    private String server_ip = "localhost";

    /**
     * Creates new form LoginForm
     */
    public LoginFrame() {
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }
    
    public LoginFrame(String server_ip) {
        this.server_ip = server_ip;
        initComponents();

        // 라디오 버튼 그룹화
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(stuRadio);
        roleGroup.add(profRadio);
        roleGroup.add(adminRadio);
        setLocationRelativeTo(null);    // GUI 가운데 정렬.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        stuRadio = new javax.swing.JRadioButton();
        profRadio = new javax.swing.JRadioButton();
        adminRadio = new javax.swing.JRadioButton();
        LoginButton = new javax.swing.JButton();
        PWtext = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LectureRoom Reservation");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel4.setText("PW");

        IDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextActionPerformed(evt);
            }
        });

        stuRadio.setText("학생");
        stuRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRadioActionPerformed(evt);
            }
        });

        profRadio.setText("교수");
        profRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profRadioActionPerformed(evt);
            }
        });

        adminRadio.setText("관리자");
        adminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioActionPerformed(evt);
            }
        });

        LoginButton.setText("로그인");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDtext)
                            .addComponent(PWtext)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stuRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profRadio)
                        .addGap(28, 28, 28)
                        .addComponent(adminRadio))
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(IDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PWtext, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profRadio)
                    .addComponent(adminRadio)
                    .addComponent(stuRadio))
                .addGap(31, 31, 31)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // 1. 입력값 가져오기
        String id = IDtext.getText();
        String pw = new String(PWtext.getPassword());
        String role = null;

        if (stuRadio.isSelected()) role = "S";
        else if (profRadio.isSelected()) role = "P";
        else if (adminRadio.isSelected()) role = "A";

        if (id == null || pw == null || role == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "해당 항목을 모두 입력하십시오.");
            return;
        }

        // 2. 대기 알림창 생성
        final javax.swing.JDialog waitDialog = new javax.swing.JDialog(this, "접속 대기 중", false); // false=다른창 선택가능(여기선 상관없음)
        waitDialog.setSize(350, 150);
        waitDialog.setLocationRelativeTo(this);
        waitDialog.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE); // 닫기 버튼 막기 (강제 대기)
        
        // 알림창 내부 UI 구성
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout());
        javax.swing.JLabel msgLabel = new javax.swing.JLabel("<html><center>현재 접속 인원이 많아 대기 중입니다.<br>순서가 되면 자동으로 로그인됩니다.<br>(잠시만 기다려주세요...)</center></html>", javax.swing.SwingConstants.CENTER);
        msgLabel.setFont(new java.awt.Font("맑은 고딕", 1, 14));
        panel.add(msgLabel, java.awt.BorderLayout.CENTER);
        waitDialog.add(panel);

        // 사용될 변수들을 final 또는 effectively final로 사용하기 위해 로컬 변수에 할당
        final String finalRole = role;
        final String serverIp = this.server_ip; // LoginFrame의 멤버변수

        // 3.별도의 스레드에서 서버 접속 시도
        new Thread(() -> {
            try {
                // TCP 서버에 접속
                deu.cse.lectureroomreservation2.client.Client client = new deu.cse.lectureroomreservation2.client.Client(serverIp, 5000);
                client.sendLoginRequest(id, pw, finalRole);

                // 여기서 대기 발생! (서버가 자리가 날 때까지 응답을 안 줌)
                // 대기하는 동안 메인 화면은 'waitDialog'를 보여주고 있음
                deu.cse.lectureroomreservation2.common.LoginStatus status = client.receiveLoginStatus();

                // 4. 서버 응답이 오면 (자리가 나서 로그인이 처리되면) 실행됨
                // UI 업데이트는 반드시 EventDispatchThread에서 수행해야 함
                javax.swing.SwingUtilities.invokeLater(() -> {
                    waitDialog.dispose(); // 대기 알림창 닫기 (자동)

                    if (!status.isLoginSuccess()) {
                        if ("DUPLICATE".equals(status.getRole())) {
                            javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, "이미 로그인 중인 계정입니다.");
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, "로그인 실패! ID, 비밀번호 또는 역할이 일치하지 않습니다.");
                        }
                        client.logout();
                        return;
                    }

                    // 로그인 성공 처리 (화면 전환)
                    try {
                        switch (status.getRole()) {
                            case "STUDENT" -> {
                                new StudentMainMenu(id, client).setVisible(true);
                                // 공지사항 체크는 별도 스레드나 invokeLater 안에서 처리 권장
                                new Thread(() -> {
                                    try {
                                        client.checkAndShowNotices(null); 
                                    } catch (Exception e) { e.printStackTrace(); }
                                }).start();
                            }
                            case "PROFESSOR" ->
                                new ProfessorMainMenu(id, client).setVisible(true);
                            case "ADMIN" ->
                                new AdminMainView(id, client).setVisible(true);
                            default -> {
                                javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, "알 수 없는 사용자 유형입니다.");
                                return;
                            }
                        }
                        LoginFrame.this.dispose(); // 로그인 창 닫기
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                });

            } catch (IOException | ClassNotFoundException e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    waitDialog.dispose(); // 에러 나면 창 닫기
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(LoginFrame.this, "서버 연결 오류: " + e.getMessage());
                });
            }
        }).start();

        // 5. 스레드 시작 후 바로 알림창 띄우기 (코드 실행은 여기서 멈추지 않고 위 스레드가 돎)
        waitDialog.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void stuRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuRadioActionPerformed

    private void profRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profRadioActionPerformed

    private void adminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtext;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PWtext;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton profRadio;
    private javax.swing.JRadioButton stuRadio;
    // End of variables declaration//GEN-END:variables
}
