/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import deu.cse.lectureroomreservation2.client.Client;
import deu.cse.lectureroomreservation2.common.ReserveManageRequest;
import deu.cse.lectureroomreservation2.common.ReserveManageResult;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jimin
 */

public class ReservationHistoryView extends javax.swing.JFrame {

    /**
     * Creates new form ReservationHistoryView
     */
    private final Client client;

    public ReservationHistoryView(Client client) {
        this.client = client;
        initComponents();
        setLocationRelativeTo(null);

        // 날짜 입력 힌트 설정
        txtDate.setText("yyyy / mm / dd");
        txtDate.setForeground(Color.GRAY);

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtDate.getText().equals("yyyy / mm / dd")) {
                    txtDate.setText("");
                    txtDate.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                String input = txtDate.getText().trim();
                if (input.isEmpty()) {
                    txtDate.setText("yyyy / mm / dd");
                    txtDate.setForeground(Color.GRAY);
                }
            }
        });
    }

    private String findUserRole(String userId) {
        try {
            if (client == null || !client.isConnected()) {
                JOptionPane.showMessageDialog(this, "서버에 연결되어 있지 않습니다.");
                return null;
            }

            String role = client.findUserRole(userId);

            if (role == null || role.isEmpty()) {
                JOptionPane.showMessageDialog(this, "사용자 역할을 찾을 수 없습니다.");
            }

            return role;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "역할 조회 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblRoomSelect = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtUserId = new javax.swing.JTextField();
        cmbRoomSelect = new javax.swing.JComboBox<>();
        lblReservationTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservationHistory = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("예약 내역 조회");

        lblUserId.setText("사용자 ID :");

        lblRoomSelect.setText("강의실 선택 :");

        lblDate.setText("날짜 선택 :");

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearch.setText("🔍 검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        cmbRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전체", "908", "911", "912", "913", "914", "915", "916", "918" }));
        cmbRoomSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomSelectActionPerformed(evt);
            }
        });

        lblReservationTableTitle.setText("예약 내역");

        tblReservationHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "사용자 ID", "강의실", "년", "월", "일", "시작 시간", "종료 시간", "요일"
            }
        ));
        jScrollPane1.setViewportView(tblReservationHistory);
        if (tblReservationHistory.getColumnModel().getColumnCount() > 0) {
            tblReservationHistory.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblReservationHistory.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblReservationHistory.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        btnEdit.setText("✏ 수정");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("🗑 삭제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReservationTableTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(190, 190, 190)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserId)
                        .addGap(12, 12, 12)
                        .addComponent(lblRoomSelect)
                        .addGap(8, 8, 8)
                        .addComponent(cmbRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserId)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate)
                    .addComponent(lblRoomSelect)
                    .addComponent(cmbRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(24, 24, 24)
                .addComponent(lblReservationTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminMainView("A", client).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        final String fUserId = txtUserId.getText().trim();
        final String fRoom = cmbRoomSelect.getSelectedItem().toString().equals("전체") ? "" : cmbRoomSelect.getSelectedItem().toString();
        final String inputDate = txtDate.getText().trim();
        String fDate = inputDate.equals("yyyy / mm / dd") ? "" : inputDate;

        if (!fDate.isEmpty()) {
            String tmp = fDate.replace(" ", "");
            String[] arr = tmp.split("/");
            if (arr.length == 3) {
                fDate = arr[0] + " / " + arr[1] + " / " + arr[2];
            }
        }

        if (!fUserId.isEmpty() || !fRoom.isEmpty() || !fDate.isEmpty()) {

            try {
                ReserveManageRequest req = new ReserveManageRequest(
                        "SEARCH", fUserId, fRoom, fDate,
                        null, null, null, null, null, null
                );

                // ✅ 람다 바깥에서 result 받아두기
                final ReserveManageResult result = client.sendReserveManageRequest(req);

                SwingUtilities.invokeLater(() -> {

                    DefaultTableModel model = (DefaultTableModel) tblReservationHistory.getModel();
                    model.setRowCount(0);

                    // 1) 서버 응답 자체 없음
                    if (result == null) {
                        JOptionPane.showMessageDialog(ReservationHistoryView.this, "서버 응답 오류입니다.");
                        return;
                    }

                    String message = result.getMessage();
                    List<String[]> list = result.getReserveList();

                    // 2) 사용자 없음
                    if ("사용자 정보 없음".equals(message)) {
                        JOptionPane.showMessageDialog(ReservationHistoryView.this, "사용자 정보를 찾을 수 없습니다.");
                        return;
                    }

                    // 3) 예약 없음
                    if ("예약 없음".equals(message) || list == null || list.isEmpty()) {
                        JOptionPane.showMessageDialog(ReservationHistoryView.this, "예약 내역이 없습니다.");
                        return;
                    }

                    // 4) 테이블 채우기
                    for (String[] row : list) {
                        model.addRow(row);
                    }

                    tblReservationHistory.revalidate();
                    tblReservationHistory.repaint();
                });

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "서버 통신 오류: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "검색 조건을 입력해주세요.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblReservationHistory.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "수정할 예약을 선택해주세요.");
            return;
        }

        String userId = tblReservationHistory.getValueAt(row, 0).toString();
        String oldRoom = tblReservationHistory.getValueAt(row, 1).toString();
        String year = tblReservationHistory.getValueAt(row, 2).toString();
        String month = tblReservationHistory.getValueAt(row, 3).toString();
        String day = tblReservationHistory.getValueAt(row, 4).toString();
        String startTime = tblReservationHistory.getValueAt(row, 5).toString();
        String endTime = tblReservationHistory.getValueAt(row, 6).toString();
        String weekDay = tblReservationHistory.getValueAt(row, 7).toString();

        String oldDateStr = String.format("%s / %s / %s / %s %s", year, month, day, startTime, endTime);
        String oldReserveInfo = String.format("%s / %s / %s", oldRoom, oldDateStr, weekDay);

        String newRoom = JOptionPane.showInputDialog(this, "새 강의실 번호 입력:", oldRoom);
        String newDate = JOptionPane.showInputDialog(this, "새 날짜 및 시간 입력 (예: yyyy / mm / dd / hh:mm hh:mm):", oldDateStr);
        String newWeekDay = JOptionPane.showInputDialog(this, "새 요일 입력:", weekDay);

        if (newRoom == null || newDate == null || newWeekDay == null) {
            JOptionPane.showMessageDialog(this, "수정이 취소되었습니다.");
            return;
        }

        try {
            String role = findUserRole(userId);
            ReserveManageRequest req = new ReserveManageRequest(
                    "UPDATE", userId, null, null,
                    oldReserveInfo, newRoom, newDate, newWeekDay, role, null
            );
            ReserveManageResult res = client.sendReserveManageRequest(req);
            JOptionPane.showMessageDialog(this, res.getMessage());
            if (res.isSuccess()) {
                btnSearchActionPerformed(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "서버 오류: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void cmbRoomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomSelectActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblReservationHistory.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "삭제할 예약을 선택해주세요.");
            return;
        }

        String userId = tblReservationHistory.getValueAt(row, 0).toString();
        String room = tblReservationHistory.getValueAt(row, 1).toString();
        String year = tblReservationHistory.getValueAt(row, 2).toString();
        String month = tblReservationHistory.getValueAt(row, 3).toString();
        String day = tblReservationHistory.getValueAt(row, 4).toString();
        String startTime = tblReservationHistory.getValueAt(row, 5).toString();
        String endTime = tblReservationHistory.getValueAt(row, 6).toString();
        String weekDay = tblReservationHistory.getValueAt(row, 7).toString();

        String dateStr = String.format("%s / %s / %s / %s %s", year, month, day, startTime, endTime);
        String reserveInfo = String.format("%s / %s / %s", room, dateStr, weekDay);

        try {
            ReserveManageRequest req = new ReserveManageRequest(
                    "DELETE", userId, null, null,
                    null, null, null, null, null, reserveInfo
            );
            ReserveManageResult res = client.sendReserveManageRequest(req);
            JOptionPane.showMessageDialog(this, res.getMessage());
            if (res.isSuccess()) {
                btnSearchActionPerformed(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "서버 오류: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbRoomSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblReservationTableTitle;
    private javax.swing.JLabel lblRoomSelect;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTable tblReservationHistory;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
